version: "3.8"
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    volumes:
      - ./app:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
