version: "3.8"
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    volumes:
      - ./app:/app
    environment:
      POSTGRES_USER: ${POSTGRESS_USER}
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRES_URL: ${POSTGRESS_URL}
      POSTGRES_DB_NAME: ${POSTGRESS_DB_NAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
