- name: Build and publish image to GCR
  uses: carbonchain/action-container-registry@v1.1
  with:
    project_id: projektprogramistyczny
    dockerfile: /app/Dockerfile
    image: gcr.io/projektprogramistyczny/fastapi-project
    service_account_key: ${{secrets.GCLOUD_AUTH}}
    build_args: POSTGRES_USER=${{secrets.POSTGRES_USER}},POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}},POSTGRES_URL=${{secrets.POSTGRES_URL}},POSTGRES_DB_NAME=${{secrets.POSTGRES_DB_NAME}},POSTGRES_PORT=${{secrets.POSTGRES_PORT}}
