name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "projekt-programistyczny" #Must be unique in Heroku
          heroku_email: "mikolaj.kaluza1999@gmail.com"
          appdir: "app"
          usedocker: true
          docker_build_args: |
            PORT
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_URL: ${{secrets.POSTGRES_URL}}
          POSTGRES_DB_NAME: ${{secrets.POSTGRES_DB_NAME}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
